### ISSUE TITLE
Couple of Naming Issues

### ISSUE THREAD

**Issue by garycjohnson** [sk-t3ch/AWS-VPC-Quickstart#1]
This is a great resource. Thanks for sharing. I copied this for use in my CloudFormation and had a couple of issues: -

For the `NatGatewayPrivateA` (and B and C) I had to change the AllocationId to be `!GetAtt ElasticIPNatGatewayPrivateA.AllocationId` as the straight use of `!Ref` failed.

Also, for `RoutePrivate` I had to change the property `InstanceId` to be `NatGatewayId`.

**Comment by sk-t3ch** [comment]
Not really sure how this happened - I must have committed and old file. Thank you!
